In [3]:
import numpy as np
from sklearn.preprocessing import Binarizer

# 特徴量を作成
age = np.array([[6],
                [12],
                [20],
                [30],
                [36],
                [65]])

# 二値化器を作成
# Create binarizer
binarizer = Binarizer(18)

# 特徴量を変換
binarizer.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1],
       [1]])

In [4]:
np.digitize(age, bins=[20,30,64])

array([[0],
       [0],
       [1],
       [2],
       [2],
       [3]])

In [5]:
np.digitize(age, bins=[20,30,64], right=True)


array([[0],
       [0],
       [0],
       [1],
       [2],
       [3]])

In [6]:
np.digitize(age, bins=[20])

array([[0],
       [0],
       [1],
       [1],
       [1],
       [1]])

In [7]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# 人工的な特徴量行列を作成
features, _ = make_blobs(n_samples = 50,
                         n_features = 2,
                         centers = 3,
                         random_state = 1)

# DataFrameを作成
dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])

# k-meansクラスタ分け器を作成
clusterer = KMeans(3, random_state=0)

# クラスタ分け器を訓練
clusterer.fit(features)

# クラスタ分けを実行
dataframe["group"] = clusterer.predict(features)

# 観測値の最初の数個を表示
dataframe.head(5)

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2